---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/dykbsgmy/public_html/
    - /usr/bin/rsync -av --exclude='.git' --exclude='*.py' --exclude='_includes/' --exclude='_frag_sig_grid_cc.html' --exclude='capital-centre/index - Capital.html' ./ $DEPLOYPATH
